config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pages#index'
  resources :wheels

  resources :coupons do
    collection do 
      post 'check_code'
    end
  end

  resources :charges


  get '/pages/about_us' => 'pages#about_us', as: 'about_us'
  get '/pages/blog' => 'pages#blog', as: 'blog'
  get '/pages/faq' => 'pages#faq', as: 'faq'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all
      else
        can :read, :all
        can :create, Wheel
      end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/charge.rb
class Charge < ActiveRecord::Base


  def self.find_by_c_id(c_id)
    if Charge.where(charge_password: c_id).present?
      Charge.where(charge_password: c_id).first
    else
      nil
    end
  end

end

app/models/coupon.rb
class Coupon < ActiveRecord::Base
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :wheels
end

app/models/wheel.rb
class Wheel < ActiveRecord::Base
  # validates :instagram_username, :image, :presence => true
  has_attached_file :image, styles: {
    thumb: '100x100>',
    square: '200x200#',
    medium: '640x640>'
  }

  # Validate the attached image is image/jpg, image/png, etc
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  belongs_to :user
  paginates_per 30
  resourcify

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  respond_to :js

  def new
  end

  def create
    begin
    # Amount in cents
      @purchase = params[:number_of_ads]
      if @purchase == "3 for $5"
        @amount = 500
      elsif @purchase == "5 $10"
        @amount = 1000
      elsif @purchase == "10 ($10)"
        @amount = 1000
      else
        @amount = 3000
      end

      customer = Stripe::Customer.create(
        :email => params[:stripeEmail],
        :card  => params[:stripeToken]
      )

      charge = Stripe::Charge.create(
        :customer    => customer.id,
        :amount      => @amount,
        :description => 'Rails Stripe customer',
        :currency    => 'usd'
      )

    rescue Stripe::CardError => e
      flash[:error] = e.message
      @error = e.message
    end
    
    if @error.present?
      redirect_to new_wheel_path, alert: "Credit Card Error, try again. #{e.message}"
    else
      @password = SecureRandom.base64
      Charge.create(email: params[:stripeEmail], amount: @amount, charge_password: @password, stripe_customer_id: customer.id, string: @purchase)
      redirect_to new_wheel_path(c_id: @password), notice: "Thank you for your purchase of #{@purchase}"
    end
  end

end

app/controllers/coupons_controller.rb
class CouponsController < ApplicationController
  respond_to :js

  def check_code
    @coupon_code = params[:coupon_code]
    if Coupon.where(code: @coupon_code).present?
      @password = SecureRandom.base64
      Charge.create(charge_password: @password, string: "coupon", amount: 00)
      redirect_to new_wheel_path(c_id: @password), notice: "Enjoy your free submission"
    else
      redirect_to new_wheel_path, alert: "Not a Valid Code"
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def about_us
  end

  def blog
  end

  def faq
  end

end

app/controllers/wheels_controller.rb
class WheelsController < ApplicationController

  def new
    @wheel = Wheel.new
    @charged = false
    @selected = nil
    if params[:amount].present?
      if params[:amount] == "3"
        @selected = "3 for $5"
      elsif params[:amount] == "5"
        @selected = "5 for $10"
      elsif params[:amount] == "unlimited"
        @selected = "Unlimited for $30"
      end
    end
    if params[:c_id].present?
      if Charge.where(charge_password: params[:c_id]).present?
        @charged = true
        @charge = Charge.find_by_c_id(params[:c_id])
      end
    end
  end

  def create
    @wheel = Wheel.new(wheel_params)
    if params[:charge_id].present?
      @wheel.charge_id = params[:charge_id].to_i
    end
    if params[:user_id].present?
      @wheel.user_id = params[:user_id].to_i
    end
    if @wheel.save
      NotificationMailer.notification(@wheel).deliver if Rails.env == "production"
      redirect_to wheel_path(@wheel), notice: "Thank you for your submission!"
    else
      render action: 'new'
    end
  end

  def show
    @wheel = Wheel.find(params[:id])
  end

  def index
    @q = Wheel.ransack(params[:q])
    @wheels = @q.result(distinct: true).order('created_at DESC')
    @admin = false
    if current_user.present?
      if current_user.roles.present?
        @admin = true
      end
    end
  end

  def destroy
    @wheel = Wheel.find(params[:id])
    @wheel.destroy
    redirect_to wheels_path, notice: "you deleted a wheel"
  end

  def edit
    @wheel = Wheel.find(params[:id])
  end

  def update
    @wheel = Wheel.find(params[:id])
    @wheel.update_attributes(wheel_params)
    redirect_to wheel_path(@wheel), notice: "nice update bro"
  end

  private

  def charge_em
    result = true
    # @amount = 500
    # customer = Stripe::Customer.create(
    #   :email => 'example@stripe.com',
    #   :card  => params[:stripeToken]
    # )
    # charge = Stripe::Charge.create(
    #   :customer    => customer.id,
    #   :amount      => @amount,
    #   :description => 'Rails Stripe customer',
    #   :currency    => 'usd'
    # )
    # rescue Stripe::CardError => e
    #   flash[:error] = e.message
    #   result = false
    # end
    # return result
  end

  def wheel_params
    params.require(:wheel).permit(:instagram_username, :make, :model, :diameter, :front_width, :rear_width, :front_offset, :rear_offset, :pcd_lug_pattern, :price, :notes, :image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in") do 
              concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
              concat message 
            end)
    end
    nil
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/create.js.erb
alert("derp");

app/views/coupons/check_code.js.erb
<% if @free_submission %>
  $('#form').show();
  $('#not-free-payment').remove();
<% else %>
  alert("Invalid Code");
<% end %>

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-default
  .container-fluid
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      =link_to(image_tag("tinylogo.png", class: "img-responsive"), root_path, class: "navbar-brand", style: "margin-top: -17px;")
      %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
    / Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li
          = link_to "Current Listings", wheels_path
        %li
          = link_to "About Us", about_us_path
          %span.sr-only (current)
      %ul.nav.navbar-nav.navbar-right
        - if current_user.present?
          %li.dropdown
            %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
              #{current_user.email}
              %span.caret
            %ul.dropdown-menu
              %li
                %a{:href => "#"} My postings
              %li
                =link_to "Log Out", destroy_user_session_path, method: :delete
        - else
          %li
            = link_to "Sign Up", new_user_registration_path
          %li
            = link_to "Log In", new_user_session_path
    / /.navbar-collapse
  / /.container-fluid

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SellinWheels</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
  <%= render "layouts/navbar" %>
 <%= flash_messages %>
<%= yield %>

</body>
</html>

app/views/pages/about_us.html.haml
%div.container.center
  %h1 About @sellinwheels:
  %p
    Sellinwheels was created to connect buyers to sellers of high end, performance wheels for all makes & models of vehicles. We are a company created by the enthusiast and for the enthusiast.
  %p
    We have developed an easy advertising system that will help you sell your wheels at a fair price, in minimal time. We will promote your "FOR SALE" or "WANTED TO BUY" advertisements to thousands of targeted wheel enthusiasts, across multiple social media platforms to ensure maximum exposure and expedite the process.
  %div.row
    %div.col-xs-6
      = image_tag("ev_in_car.jpg", class: "img-responsive img-rounded")
    %div.col-xs-6
      = image_tag("ev-dog.jpg", class: "img-responsive img-rounded")
  %h3 About Me:
  %p
    I'm Evan Beckerman, mechanical engineer, and wheel connoisseur. I have been working with fitments, refinishing wheels, and involved in the automotive industry for over 10 years. I have a passion for helping people find what they are looking for, even when its rare or discontinued! Please feel free to email me with any questions or comments about the site or the vision for @sellinwheels. Please email us at Sellinwheels@gmail.com

app/views/pages/blog.html.haml
%div.container.center
  %h1 Blog
  %h5 Coming soon...

app/views/pages/faq.html.haml
%div.container
  .jumbotron
    %h1 FAQ!
    %p ...
    %p
      %a.btn.btn-primary.btn-lg{:href => "#", :role => "button"} Learn more

app/views/pages/index.html.haml
#carousel-example-generic.carousel.slide{"data-ride" => "carousel"}
  / Indicators
  %ol.carousel-indicators
    %li.active{"data-slide-to" => "0", "data-target" => "#carousel-example-generic"}
    %li{"data-slide-to" => "1", "data-target" => "#carousel-example-generic"}
    %li{"data-slide-to" => "2", "data-target" => "#carousel-example-generic"}
    %li{"data-slide-to" => "3", "data-target" => "#carousel-example-generic"}
    %li{"data-slide-to" => "4", "data-target" => "#carousel-example-generic"}
    %li{"data-slide-to" => "5", "data-target" => "#carousel-example-generic"}
  / Wrapper for slides
  .carousel-inner{:role => "listbox"}
    .item.active
      = image_tag("tryagain.jpg", class: "img-responsive")
    .item
      = image_tag("D-Chan copy.jpg", class: "img-responsive")
    .item
      = image_tag("hrebanner2.jpg", class: "img-responsive")
    .item
      = image_tag("banner3.jpg", class: "img-responsive")
    .item
      = image_tag("banner4.jpg", class: "img-responsive")
    .item
      = image_tag("banner5.jpg", class: "img-responsive")
  / Controls
  %a.left.carousel-control{"data-slide" => "prev", :href => "#carousel-example-generic", :role => "button"}
    %span{"aria-hidden" => "true"} <
    %span.sr-only Previous
  %a.right.carousel-control{"data-slide" => "next", :href => "#carousel-example-generic", :role => "button"}
    %span{"aria-hidden" => "true"} >
    %span.sr-only Next
%div.container
  %div.row
    %div.col-lg-12.text-center
      %h1 How it works
  %div.row
    %div.col-lg-6.col-lg-offset-4
      %p{style: "align: left;"}
        %ul#main-list
          %li 1. Select the quantity of listings you would like posted.
          %li 2. Register your email to receive results & feedback
          %li 3. Fill out the simple Instagram form
          %li 4. Your listing will be featured in 24 hours or less!
          %li (Limit 1 Ad per day.)
  %div.row
    %div.col-lg-3.text-center
      .thumbnail
        = image_tag("1.jpg", class: "img-responsive")
        .caption
          %h3 FREE!
          %p 
            One Free Instagram post on the @sellinwheels account
          %p
            = link_to "Free!", new_wheel_path(amount: 1), class: "btn btn-primary"
    %div.col-lg-3.text-center
      .thumbnail
        = image_tag("3.jpg", class: "img-responsive")
        .caption
          %h3 $5
          %p 
            Three Instagram posts on the @sellinwheels account
          %p
            = link_to "Purchase", new_wheel_path(amount: 3), class: "btn btn-primary"
    %div.col-lg-3.text-center
      .thumbnail
        = image_tag("5.jpg", class: "img-responsive")
        .caption
          %h3 $10
          %p 
            Five Instagram posts on the @sellinwheels account
          %p
            = link_to "Purchase", new_wheel_path(amount: 5), class: "btn btn-primary"
    %div.col-lg-3.text-center
      .thumbnail
        = image_tag("Infinity.jpg", class: "img-responsive")
        .caption
          %h3 $30
          %p 
            Unlimited Instagram posts on the @sellinwheels account
          %p
            = link_to "Purchase", new_wheel_path(amount: "unlimited"), class: "btn btn-primary"

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/wheels/_form.html.haml
= form_for(@wheel, multipart: true, :html => {:class => "form-horizontal"}) do |f|
  - if current_user.present?
    = hidden_field_tag :user_id, current_user.id
  - if @charged
    = hidden_field_tag :charge_id, @charge.id
  %div.form-group
    = f.label "Instagram Username", class: "col-xs-5 control-label"
    %div.col-xs-3
      = f.text_field :instagram_username, class: 'form-control', placeholder: "ex. @sellinwheels"
  %div.form-group
    = f.label :wheel_make, class: "col-xs-5 control-label"
    %div.col-xs-3
      = f.select :make, options_for_select(["HRE Wheels","Oz Racing Wheels","ADV1 Wheels","Morr Wheels","BBS Wheels","Work Wheels","Advan Wheels","Volk/Rays","Hayashi Racing","Vossen Wheels","Kinesis","Techart","CCW Wheels","Rotiform","BLK Wheels","Ronal Wheels","Wedsport","Iforged","Aristo Collection","360 forged","Forgeline","SSR","DPE","AG Wheels","Strasse Forged","Other"].sort), {prompt: "Select Make"}, {required: 'true', autofocus: 'true', class: 'form-control'}
  %div.form-group
    = f.label :wheel_model, class: "col-xs-5 control-label"
    %div.col-xs-3
      = f.text_field :model, class: 'form-control'
  %div.form-group
    = f.label :diameter, class: "col-xs-5 control-label"
    %div.col-xs-3
      = f.select :diameter, options_for_select(['15"','16"','17"','18"','19"','20"','21"','other']), {prompt: "Choose Diameter"}, {class: "form-control"}
  %div.form-group
    = f.label :front_width, class: "col-xs-5 control-label"
    %div.col-xs-3
      = f.select :front_width, options_for_select(['5.5"','6.0"','6.5"','7.0"','7.5"','8.0"','8.5"','9.0"','9.5"','10.0"','10.5"','11.0"','11.5"','12.0"','other']), {prompt: "Choose Front Width"}, {class: "form-control"}
  %div.form-group
    = f.label :front_offset, class: "col-xs-5 control-label"
    %div.col-xs-3
      = f.text_field :front_offset, class: 'form-control', placeholder: "ex. +30"
  %div.form-group
    = f.label :rear_width, class: "col-xs-5 control-label"
    %div.col-xs-3
      = f.select :rear_width, options_for_select(['5.5"','6.0"','6.5"','7.0"','7.5"','8.0"','8.5"','9.0"','9.5"','10.0"','10.5"','11.0"','11.5"','12.0"','other']), {prompt: "Choose Rear Width"}, {class: "form-control"}
  %div.form-group
  %div.form-group
    = f.label :rear_offset, class: "col-xs-5 control-label"
    %div.col-xs-3
      = f.text_field :rear_offset, class: 'form-control', placeholder: "ex. +30"
  %div.form-group
    = f.label :pcd_lug_pattern, class: "col-xs-5 control-label"
    %div.col-xs-3
      = f.select :pcd_lug_pattern, options_for_select(["4x100","4x114.3","5x100","5x112","5x114.3","5x120","5x130","other"]), {prompt: "PCD Lug Pattern"}, {class: "form-control"}
  %div.form-group
    = f.label :price, class: "col-xs-5 control-label"
    %div.col-xs-3
      = f.text_field :price, class: 'form-control'
  %div.form-group
    = f.label "notes/hashtags", class: "col-xs-5 control-label"
    %div.col-xs-3
      = f.text_area :notes, class: 'form-control'
  %div.form-group
    = f.label "image", class: "col-xs-5 control-label"
    %div.col-xs-3
      %p
        = f.file_field :image
  %div.form-group
    = submit_tag "Submit!", class: "btn btn-primary"

app/views/wheels/_free_submission.html.haml
= form_tag charges_path do
  %div#payment-options
    %div.form-group
      = label_tag "Select Number of Ads", nil, class: "col-md-3 control-label"
      %div.col-lg-9
        = select_tag :number_of_ads, options_for_select(["1 ($3)", "3 ($7)", "5 ($10)", "* Offer in 30 days or less or full refund ($30)"])
    %div.row
      %div.col-xs-6.col-xs-offset-3
        .actions
          %script.stripe-button{ src: "https://checkout.stripe.com/checkout.js", data: {description: "Purchase", label: "Purchase", key: ENV["STRIPE_PUBLISHABLE_KEY"], name: "Sellin Wheels"}}

app/views/wheels/_purchase_form.html.haml
= form_tag charges_path do
  %div#payment-options
    %div.form-group
      = label_tag "Select Number of Ads", nil, class: "col-md-3 control-label"
      %div.col-lg-9
        = select_tag :number_of_ads, options_for_select(["3 for $5", "5 for $10", "Unlimited for $30"], selected: @selected)
    %div.row
      %div.col-xs-6.col-xs-offset-3
        .actions
          %script.stripe-button{ src: "https://checkout.stripe.com/checkout.js", data: {description: "Purchase", label: "Purchase", key: ENV["STRIPE_PUBLISHABLE_KEY"], name: "Sellin Wheels"}}

app/views/wheels/edit.html.haml
%div.container
  %div.row#form
    %div.row
      %div.col-xs-12.text-center
        %h5 Please fill out as much as you can
        = render "form"

app/views/wheels/index.html.haml
%div.container
  = search_form_for @q do |f|
    #{f.label :wheel_make}
    #{f.select :make_cont, options_for_select(["HRE Wheels","Oz Racing Wheels","ADV1 Wheels","Morr Wheels","BBS Wheels","Work Wheels","Advan Wheels","Volk/Rays","Hayashi Racing","Vossen Wheels","Kinesis","Techart","CCW Wheels","Rotiform","BLK Wheels","Ronal Wheels","Wedsport","Iforged","Aristo Collection","360 forged","Forgeline","SSR","DPE","AG Wheels","Strasse Forged","Other"].sort), prompt: "Search Make"}
    #{f.label :diameter}
    #{f.select :diameter_cont, options_for_select(['15"','16"','17"','18"','19"','20"','21"','other']), prompt: "Search Diameter"}
    #{f.label :pcd_lug_pattern}
    #{f.select :pcd_lug_pattern_cont, options_for_select(["4x100","4x114.3","5x100","5x112","5x114.3","5x120","5x130","other"]), prompt: "Search PCD Lug Pattern"}
    #{f.submit class: "btn btn-primary"}
    #{link_to "Clear Search", wheels_path, class: "btn btn-danger" if params[:q].present?} 
  %h1 Current Listings
  - @wheels.in_groups_of(4, false).each do |wheel_group|
    .row
      -wheel_group.each do |wheel|
        .col-lg-3
          .thumbnail
            - if wheel.image.present?
              = image_tag wheel.image.url(:medium, timestamp:false), class: "img-responsive" 
            - else
              = image_tag("no-img-placeholder.png", class: "img-responsive")
            .caption
              %b #{wheel.make} | #{wheel.model}
              %p  
                Submitted by @#{wheel.instagram_username}
                %br/
                %small #{distance_of_time_in_words(wheel.created_at, DateTime.now)} ago
              %p
                = link_to "View Post", wheel_path(wheel), class: "btn btn-primary"
                = link_to "DESTROY", wheel_path(wheel), method: :delete, class: "btn btn-danger", :data => {:confirm => 'You sure you wanna do that boi?'} if @admin
                = link_to "Modify", edit_wheel_path(wheel), class: "btn btn-info" if @admin
  / # = paginate @wheels, :theme => 'twitter-bootstrap-3'

app/views/wheels/new.html.haml
%div.container
  %div.row
    %div.col-xs-12.text-center
      = image_tag("logo.jpg")
  / - unless @charged
  /   %div.row#payment
  /     %div.col-lg-12
  /       %div.form-group
  /         = form_tag("/coupons/check_code") do
  /           = label_tag "Coupon Code", nil, class: "col-xs-3 control-label"
  /           %div.col-xs-6
  /             = text_field_tag :coupon_code, nil,  class: "form-control"
  /           %div.col-xs-3
  /             = submit_tag "Apply", class: "btn btn-default"
  - if @charged || params[:amount] == "1"
    %div.row#form
      %div.row
        %div.col-xs-12.text-center
          %h5 Please fill out as much as you can
      %div.col.xs-3.text-center
        = render "form"
  - if current_user.present?
    - if current_user.wheels.count == 0
      %div.row#form
        %div.row
          %div.col-xs-12.text-center
            %h5 Thanks for Signing up. Enjoy your first post on us!
        %div.col.xs-3.text-center
          = render "form"
    - else
      - unless params[:amount] == "1"
        = render "purchase_form"
  - else
    - unless @charged || params[:amount] == "1"
      = render "purchase_form"

app/views/wheels/show.html.haml
%div.row
  %div.col-xs-12.text-center
    = image_tag("logo.jpg")
%div.row
  %div.col-xs-8.col-xs-offset-2
    .panel.panel-default
      .panel-heading.text-center
        %h3.panel-title #{@wheel.instagram_username} Submission
      .panel-body
        %div.row
          %div.col.xs-12.text-center
            = image_tag @wheel.image.url(:medium, timestamp:false), class: 'img-responsive'
        %div.row
          %div.col-xs-12
            %p
              &nbsp
            FOR SALE BY:
            %br
            ="@#{@wheel.instagram_username}"
            %br
            MAKE: ##{@wheel.make}
            %br
            MODEL: ##{@wheel.model}
            %br
            DIAMETER: #{@wheel.diameter}"
            %br
            F: WIDTH: #{@wheel.front_width}(")
            %br
            F: OFFSET: #{@wheel.front_offset}
            %br
            R: WIDTH : #{@wheel.rear_width} (")
            %br
            R: OFFSET: #{@wheel.rear_offset}
            %br
            PCD / LUG PATTERN: #{@wheel.pcd_lug_pattern}
            %br
            PRICE: $ #{@wheel.price}
            %br
            NOTES/COMMENTS: #{@wheel.notes}
            %br
            = "#wheelsforsale"            
            %br
            = "#sellinwheels"
            %br
            = "#realwheels"
            %br
            = "#fitment"
            %br
            = "#wheels"            
            %br
            = "#forged"
            %br
            = "#fitted"            
            %br
            = "#flush"            
            %br            
            = "#cars"
            %br
            = "#go"